In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]

In [3]:
ar=np.array(l)

In [4]:
type(ar)

numpy.ndarray

In [5]:
ar1=np.array([[1,2],[3,4]])

In [6]:
(ar1)

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray(l)

array([1, 2, 3, 4])

In [8]:
b=np.matrix(l)

In [9]:
b

matrix([[1, 2, 3, 4]])

In [10]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [11]:
a=np.array(l)

In [12]:
a

array([1, 2, 3, 4])

In [13]:
c=a

In [14]:
a

array([1, 2, 3, 4])

In [15]:
c

array([1, 2, 3, 4])

In [16]:
c[0]=1000

In [17]:
c

array([1000,    2,    3,    4])

In [18]:
a

array([1000,    2,    3,    4])

In [19]:
a[1]=2000

In [20]:
a

array([1000, 2000,    3,    4])

In [21]:
c

array([1000, 2000,    3,    4])

In [22]:
d=np.copy(a)

In [23]:
d

array([1000, 2000,    3,    4])

In [24]:
a

array([1000, 2000,    3,    4])

In [25]:
a[3]=4000

In [26]:
a

array([1000, 2000,    3, 4000])

In [27]:
d

array([1000, 2000,    3,    4])

In [28]:
np.fromfunction(lambda i, j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [29]:
np.fromfunction(lambda i,j: i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [30]:
iterable=(i*i for i in range(5))

In [31]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [32]:
np.fromstring('234 234 ', sep=" ")

array([234., 234.])

In [33]:
np.fromstring('4,5 ', sep=" , ")

array([4., 5.])

In [34]:
#Numpy= Data types

In [35]:
l=[2,3,4]

In [36]:
ar=np.array(l)

In [37]:
ar

array([2, 3, 4])

In [38]:
ar.ndim

1

In [39]:
ar3=np.array([[1,2,3,4], [2,3,4,5]])

In [40]:
ar3.ndim

2

In [41]:
ar3

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [42]:
ar4=np.array([[1,2,3,4], [2,3,4,5],[5,6,4,7]])

In [43]:
ar4.ndim

2

In [44]:
ar4.size

12

In [45]:
ar3.shape

(2, 4)

In [46]:
ar4.shape

(3, 4)

In [50]:
ar3.dtype

dtype('int32')

In [51]:
ar22=np.array([(1.4,45,58,), (65,45,32)])

In [52]:
ar22

array([[ 1.4, 45. , 58. ],
       [65. , 45. , 32. ]])

In [53]:
ar22.dtype

dtype('float64')

In [56]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [63]:
list(np.arange(2.3,5.4,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [64]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [66]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [68]:
z=np.zeros((3,4,2))

In [69]:
z

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [70]:
z.ndim

3

In [73]:
z1=np.zeros((3,4,2,3))

In [74]:
z1

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [75]:
z1.dtype

dtype('float64')

In [76]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [81]:
k=np.ones((2,3,4))

In [82]:
k+5

array([[[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]],

       [[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]]])

In [83]:
k*4

array([[[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]],

       [[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]]])

In [84]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [85]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [86]:
np.linspace(2,4, 20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [87]:
np.logspace(2,5,10, base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [90]:
t=np.random.randn(3,4)

In [91]:
t

array([[-1.55493954,  1.19223541, -1.1061359 ,  1.06656114],
       [-0.67831026, -0.15853522, -1.89817857, -1.69405029],
       [ 1.44007045, -0.02880112,  0.82026485, -0.15539666]])

In [89]:
import pandas as pd

In [92]:
pd.DataFrame(t)

0         1         2         3
0 -1.55494  1.192235 -1.106136  1.066561
1 -0.67831 -0.158535 -1.898179 -1.694050
2  1.44007 -0.028801  0.820265 -0.155397

In [93]:
np.random.randn(3,4)

array([[-0.57383109,  1.64627954, -0.56646667, -0.55507115],
       [ 1.31310549,  1.05329644, -1.41964038,  1.58686103],
       [ 0.47080428, -0.92954242, -1.07704386,  0.27346722]])

In [94]:
np.random.randint(1,110,(3,4))

array([[ 50,  19,  50,  38],
       [ 85,  75, 105,  44],
       [ 54, 107, 101,  61]])

In [95]:
t=np.random.randn(3,4)

In [96]:
t

array([[-0.59743546, -0.19046834, -0.03126732, -1.03040227],
       [-0.0901289 , -1.63757208,  2.00853515, -1.37396076],
       [-0.46996781, -0.35440441,  0.90502227,  0.07110176]])

In [103]:
t.reshape(6,2)

array([[-0.59743546, -0.19046834],
       [-0.03126732, -1.03040227],
       [-0.0901289 , -1.63757208],
       [ 2.00853515, -1.37396076],
       [-0.46996781, -0.35440441],
       [ 0.90502227,  0.07110176]])

In [104]:
t

array([[-0.59743546, -0.19046834, -0.03126732, -1.03040227],
       [-0.0901289 , -1.63757208,  2.00853515, -1.37396076],
       [-0.46996781, -0.35440441,  0.90502227,  0.07110176]])

In [106]:
t[1][2]

2.008535147390177

In [111]:
t[0:3,1]

array([-0.19046834, -1.63757208, -0.35440441])

In [112]:
h=np.random.randint(1,100,(5,5))

In [113]:
h

array([[11, 12, 24, 40, 47],
       [69, 37, 43, 81, 28],
       [64,  8, 19, 26, 80],
       [53, 72, 95, 47, 50],
       [66, 85, 73, 94,  5]])

In [114]:
h>50

array([[False, False, False, False, False],
       [ True, False, False,  True, False],
       [ True, False, False, False,  True],
       [ True,  True,  True, False, False],
       [ True,  True,  True,  True, False]])

In [116]:
h[h>50]

array([69, 81, 64, 80, 53, 72, 95, 66, 85, 73, 94])

In [119]:
h[2:4,[1,2]]

array([[ 8, 19],
       [72, 95]])

In [120]:
h

array([[11, 12, 24, 40, 47],
       [69, 37, 43, 81, 28],
       [64,  8, 19, 26, 80],
       [53, 72, 95, 47, 50],
       [66, 85, 73, 94,  5]])

In [122]:
h[0][0]=5000

In [123]:
h

array([[5000,   12,   24,   40,   47],
       [  69,   37,   43,   81,   28],
       [  64,    8,   19,   26,   80],
       [  53,   72,   95,   47,   50],
       [  66,   85,   73,   94,    5]])

In [126]:
h1=np.random.randint(1,3,(3,3))
h2=np.random.randint(1,3,(3,3))

In [127]:
h1

array([[2, 2, 2],
       [1, 2, 1],
       [2, 2, 1]])

In [128]:
h2

array([[2, 2, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [129]:
h1+h2

array([[4, 4, 3],
       [3, 4, 3],
       [4, 4, 3]])

In [130]:
h1-h2

array([[ 0,  0,  1],
       [-1,  0, -1],
       [ 0,  0, -1]])

In [131]:
h1*h2

array([[4, 4, 2],
       [2, 4, 2],
       [4, 4, 2]])

In [132]:
h1/0

C:\Users\anura\AppData\Local\Temp\ipykernel_11828\2245976697.py:1: RuntimeWarning: divide by zero encountered in true_divide
  h1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [133]:
h1**2

array([[4, 4, 4],
       [1, 4, 1],
       [4, 4, 1]], dtype=int32)

In [134]:
#Numpy -broadcast.

In [135]:
g=np.zeros((4,4))

In [136]:
g

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [138]:
roe=np.array([1,2,3,4])

In [139]:
roe


array([1, 2, 3, 4])

In [140]:
g+roe

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [141]:
col=np.array([[1,2,3,4]])

In [142]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [145]:
y=np.random.randint(1,4,(3,4))

In [146]:
y

array([[2, 1, 3, 3],
       [2, 2, 2, 2],
       [1, 2, 1, 2]])

In [147]:
np.sqrt(y)

array([[1.41421356, 1.        , 1.73205081, 1.73205081],
       [1.41421356, 1.41421356, 1.41421356, 1.41421356],
       [1.        , 1.41421356, 1.        , 1.41421356]])

In [148]:
np.exp(y)

array([[ 7.3890561 ,  2.71828183, 20.08553692, 20.08553692],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 ,  7.3890561 ],
       [ 2.71828183,  7.3890561 ,  2.71828183,  7.3890561 ]])

In [149]:
np.log10(y)

array([[0.30103   , 0.        , 0.47712125, 0.47712125],
       [0.30103   , 0.30103   , 0.30103   , 0.30103   ],
       [0.        , 0.30103   , 0.        , 0.30103   ]])

In [150]:
y.dtype

dtype('int32')