In [1]:
import numpy as np

In [2]:
arr=np.random.randint(1,10,(3,4))

In [3]:
arr

array([[5, 3, 2, 5],
       [5, 3, 2, 8],
       [7, 4, 1, 6]])

In [4]:
arr.reshape(6,2)

array([[5, 3],
       [2, 5],
       [5, 3],
       [2, 8],
       [7, 4],
       [1, 6]])

In [5]:
arr.reshape(2,6)

array([[5, 3, 2, 5, 5, 3],
       [2, 8, 7, 4, 1, 6]])

In [6]:
arr.T

array([[5, 5, 7],
       [3, 3, 4],
       [2, 2, 1],
       [5, 8, 6]])

In [7]:
arr.flatten()

array([5, 3, 2, 5, 5, 3, 2, 8, 7, 4, 1, 6])

In [8]:
arr1=np.array([1,2,3,4,5])

In [9]:
arr1.ndim

1

In [10]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [11]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 4, 5]])

In [12]:
arr

array([[5, 3, 2, 5],
       [5, 3, 2, 8],
       [7, 4, 1, 6]])

In [13]:
np.squeeze(arr)

array([[5, 3, 2, 5],
       [5, 3, 2, 8],
       [7, 4, 1, 6]])

In [16]:
data=np.array([[1],[2],[3]])

In [17]:
data

array([[1],
       [2],
       [3]])

In [18]:
np.squeeze(data)

array([1, 2, 3])

In [19]:
arr1

array([1, 2, 3, 4, 5])

In [20]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [21]:
np.roll(arr1,2)

array([4, 5, 1, 2, 3])

In [22]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [23]:
#Numpy - Bineary Operators.

In [25]:
arr1=np.random.randint(1,10,(3,4))

In [35]:
arr1

array([[8, 5, 5, 1],
       [9, 2, 9, 2],
       [7, 9, 9, 9]])

In [28]:
arr2=np.random.randint(1,10,(3,4))

In [29]:
arr1+arr2

array([[16,  7, 10,  5],
       [16,  7, 17,  8],
       [14, 11, 12, 14]])

In [30]:
arr1-arr2

array([[ 0,  3,  0, -3],
       [ 2, -3,  1, -4],
       [ 0,  7,  6,  4]])

In [31]:
arr1*arr2

array([[64, 10, 25,  4],
       [63, 10, 72, 12],
       [49, 18, 27, 45]])

In [32]:
arr1/arr2

array([[1.        , 2.5       , 1.        , 0.25      ],
       [1.28571429, 0.4       , 1.125     , 0.33333333],
       [1.        , 4.5       , 3.        , 1.8       ]])

In [33]:
arr1%arr2

array([[0, 1, 0, 1],
       [2, 2, 1, 2],
       [0, 1, 0, 4]], dtype=int32)

In [34]:
arr1**arr2

array([[16777216,       25,     3125,        1],
       [ 4782969,       32, 43046721,       64],
       [  823543,       81,      729,    59049]], dtype=int32)

In [36]:
arr1&arr2

array([[8, 0, 5, 0],
       [1, 0, 8, 2],
       [7, 0, 1, 1]], dtype=int32)

In [37]:
~arr1

array([[ -9,  -6,  -6,  -2],
       [-10,  -3, -10,  -3],
       [ -8, -10, -10, -10]], dtype=int32)

In [38]:
arr1|arr2

array([[ 8,  7,  5,  5],
       [15,  7,  9,  6],
       [ 7, 11, 11, 13]], dtype=int32)

In [39]:
arr1>arr2

array([[False,  True, False, False],
       [ True, False,  True, False],
       [False,  True,  True,  True]])

In [40]:
arr1<arr2

array([[False, False, False,  True],
       [False,  True, False,  True],
       [False, False, False, False]])

In [41]:
# Numpy -String Functions

In [44]:
p=np.array(["such" , "kumar"])

In [46]:
np.char.upper(p)

array(['SUCH', 'KUMAR'], dtype='<U5')

In [48]:
np.char.title(p)

array(['Such', 'Kumar'], dtype='<U5')

In [52]:
np.char.capitalize(p)

array(['Such', 'Kumar'], dtype='<U5')

In [53]:
# numpy - mathematical Functions.

In [54]:
arr1

array([[8, 5, 5, 1],
       [9, 2, 9, 2],
       [7, 9, 9, 9]])

In [55]:
np.sin(arr1)

array([[ 0.98935825, -0.95892427, -0.95892427,  0.84147098],
       [ 0.41211849,  0.90929743,  0.41211849,  0.90929743],
       [ 0.6569866 ,  0.41211849,  0.41211849,  0.41211849]])

In [56]:
np.cos(arr1)

array([[-0.14550003,  0.28366219,  0.28366219,  0.54030231],
       [-0.91113026, -0.41614684, -0.91113026, -0.41614684],
       [ 0.75390225, -0.91113026, -0.91113026, -0.91113026]])

In [57]:
np.tan(arr1)

array([[-6.79971146, -3.38051501, -3.38051501,  1.55740772],
       [-0.45231566, -2.18503986, -0.45231566, -2.18503986],
       [ 0.87144798, -0.45231566, -0.45231566, -0.45231566]])

In [58]:
np.tanh(arr1)

array([[0.99999977, 0.9999092 , 0.9999092 , 0.76159416],
       [0.99999997, 0.96402758, 0.99999997, 0.96402758],
       [0.99999834, 0.99999997, 0.99999997, 0.99999997]])

In [59]:
np.log10(arr1)

array([[0.90308999, 0.69897   , 0.69897   , 0.        ],
       [0.95424251, 0.30103   , 0.95424251, 0.30103   ],
       [0.84509804, 0.95424251, 0.95424251, 0.95424251]])

In [60]:
np.exp(arr1)

array([[2.98095799e+03, 1.48413159e+02, 1.48413159e+02, 2.71828183e+00],
       [8.10308393e+03, 7.38905610e+00, 8.10308393e+03, 7.38905610e+00],
       [1.09663316e+03, 8.10308393e+03, 8.10308393e+03, 8.10308393e+03]])

In [61]:
np.power(arr1,2)

array([[64, 25, 25,  1],
       [81,  4, 81,  4],
       [49, 81, 81, 81]], dtype=int32)

In [62]:
np.sqrt(arr1)

array([[2.82842712, 2.23606798, 2.23606798, 1.        ],
       [3.        , 1.41421356, 3.        , 1.41421356],
       [2.64575131, 3.        , 3.        , 3.        ]])

In [63]:
np.median(arr1)

7.5

In [65]:
np.mean(arr1)

6.25

In [ ]:
n