In [1]:
import numpy as np

In [3]:
arr=np.array([4,5,6,7,8,9,1,2,3])

In [4]:
arr

array([4, 5, 6, 7, 8, 9, 1, 2, 3])

In [5]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.searchsorted(arr,6)

2

In [7]:
arr1=np.array([0,345,687,0,0,0,0,0,0,0,0])

In [8]:
np.count_nonzero(arr1)

2

In [9]:
arr

array([4, 5, 6, 7, 8, 9, 1, 2, 3])

In [10]:
np.where(arr>6)

(array([3, 4, 5], dtype=int64),)

In [11]:
np.extract(arr>6,arr)

array([7, 8, 9])

In [12]:
# Numpy byte Swapping

In [13]:
arr.byteswap()

array([ 67108864,  83886080, 100663296, 117440512, 134217728, 150994944,
        16777216,  33554432,  50331648])

In [14]:
# Numpy - copies & Views.

In [16]:
arr

array([4, 5, 6, 7, 8, 9, 1, 2, 3])

In [17]:
a=np.copy(arr)

In [18]:
b=arr.view()

In [19]:
b

array([4, 5, 6, 7, 8, 9, 1, 2, 3])

In [20]:
b[0]=68

In [21]:
b

array([68,  5,  6,  7,  8,  9,  1,  2,  3])

In [22]:
arr

array([68,  5,  6,  7,  8,  9,  1,  2,  3])

In [23]:
# numpy - Matrix library

In [25]:
import numpy.matlib as nm

In [26]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [27]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [29]:
# Numpy - Liner Algebra

In [33]:
arr1= np.random.randint(([2,3], [4,5]))

In [34]:
arr2= np.random.randint(([5,3], [2,5]))

In [35]:
np.dot(arr1,arr2)

array([[0, 0],
       [2, 1]])

In [36]:
arr1@arr2

array([[0, 0],
       [2, 1]])